// <auto-generated />
namespace ChatBook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddGenreToBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGenreToBook));

        string IMigrationMetadata.Id
        {
            get { return "20250323160000_AddGenreToBook"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return "6.5.1"; }
        }


    }
}
